### ISSUE TITLE
how to specify the time zone

### ISSUE THREAD

**Issue by charliedream1** [ddsky/world-news-api-clients#10]
I want to search news in realtime. However, I found I can't specify the time zone for search, and all the news time with different time zone.  I might miss some news if I use local time to extract news every hour.

1. So what is the max latency should I use for real time acquisition?
2. What is the time zone used in publish time?

**Comment by ddsky** [comment]
1. Max latency is 24 hours but realistically it is minutes to a few hours after being published
2. We always try to get UTC but sometimes the source does not specify that.

You could simply sort descending by publish-time to make sure you get the latest news.

Also, I recommend using the discord for questions like these: https://discord.gg/GrmNknKHYD

**Comment by charliedream1** [comment]
Thanks



---Original---
From: "David ***@***.***&gt;
Date: Mon, Oct 14, 2024 01:30 AM
To: ***@***.***&gt;;
Cc: "Optimus ***@***.******@***.***&gt;;
Subject: Re: [ddsky/world-news-api-clients] how to specify the time zone(Issue #10)




  
Max latency is 24 hours but realistically it is minutes to a few hours after being published
 
We always try to get UTC but sometimes the source does not specify that.
  
You could simply sort descending by publish-time to make sure you get the latest news.
 
Also, I recommend using the discord for questions like these: https://discord.gg/GrmNknKHYD

**Comment by charliedream1** [comment]
For latency, do you mean UTC time?So If I sample with UTC - 24(hours), then I won't miss any news?




天天高兴！
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ddsky/world-news-api-clients"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月14日(星期一) 凌晨1:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ddsky/world-news-api-clients] how to specify the time zone (Issue #10)





  
Max latency is 24 hours but realistically it is minutes to a few hours after being published
 
We always try to get UTC but sometimes the source does not specify that.
  
You could simply sort descending by publish-time to make sure you get the latest news.
 
Also, I recommend using the discord for questions like these: https://discord.gg/GrmNknKHYD

**Comment by ddsky** [comment]
> For latency, do you mean UTC time?So If I sample with UTC - 24(hours), then I won't miss any news? 天天高兴！ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ddsky/world-news-api-clients" ***@***.***&gt;; 发送时间:&nbsp;2024年10月14日(星期一) 凌晨1:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ddsky/world-news-api-clients] how to specify the time zone (Issue #10) Max latency is 24 hours but realistically it is minutes to a few hours after being published We always try to get UTC but sometimes the source does not specify that. You could simply sort descending by publish-time to make sure you get the latest news. Also, I recommend using the discord for questions like these: https://discord.gg/GrmNknKHYD — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

correct

**Comment by charliedream1** [comment]
Thx



---Original---
From: "David ***@***.***&gt;
Date: Mon, Oct 14, 2024 23:27 PM
To: ***@***.***&gt;;
Cc: "Optimus ***@***.******@***.***&gt;;
Subject: Re: [ddsky/world-news-api-clients] how to specify the time zone(Issue #10)




  
For latency, do you mean UTC time?So If I sample with UTC - 24(hours), then I won't miss any news? 天天高兴！ @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ddsky/world-news-api-clients" @.&gt;; 发送时间:&nbsp;2024年10月14日(星期一) 凌晨1:30 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ddsky/world-news-api-clients] how to specify the time zone (Issue #10) Max latency is 24 hours but realistically it is minutes to a few hours after being published We always try to get UTC but sometimes the source does not specify that. You could simply sort descending by publish-time to make sure you get the latest news. Also, I recommend using the discord for questions like these: https://discord.gg/GrmNknKHYD — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
correct

**Comment by charliedream1** [comment]
for returned parameter publish_date, is it the news actual publish time writen in the news, or is it the time you logged into the database? 

And the publish_date might be of any time zone, it's not a fixed time zone?

**Comment by ddsky** [comment]
that's the actual publish time specified by the source. It can be any time zone, because the news could come from Australia and if they just write "October 15th, 8:50am" we have to take that time. Sometimes that do write it with UTC offsets though.

**Comment by charliedream1** [comment]
Thx 4 your reply



---Original---
From: "David ***@***.***&gt;
Date: Tue, Oct 15, 2024 16:58 PM
To: ***@***.***&gt;;
Cc: "Optimus ***@***.******@***.***&gt;;
Subject: Re: [ddsky/world-news-api-clients] how to specify the time zone(Issue #10)




 
that's the actual publish time specified by the source. It can be any time zone, because the news could come from Australia and if they just write "October 15th, 8:50am" we have to take that time. Sometimes that do write it with UTC offsets though.
