### ISSUE TITLE
how to use semantic searching with many conditions together

### ISSUE THREAD

**Issue by charliedream1** [ddsky/world-news-api-clients#11]
1. If I want to combine location, people and oraganization, how to transmit params in python, should I connect with "," or "&"
2. How to use 2 locations, if I want to limit the location for both "Austraila" and "Italy", is that possible to do so ?

**Comment by ddsky** [comment]
1. You can comma separate them, e.g. `entities=ORG:Tesla,PER:Elon Musk`
2. You can only search for one location at once. You'd have to do two requests and merge them.

**Comment by charliedream1** [comment]
thx, I see
