### ISSUE TITLE
Suggestion: Filtering by category

### ISSUE THREAD

**Issue by Boscop** [ddsky/world-news-api-clients#3]
Would it be possible to add category field to each news article in the response, and allow filtering by category?
(Other news APIs have that feature, it would be very useful.)

**Comment by ddsky** [comment]
@Boscop I agree and we have thought about that. The only "problem" is what categories should we have and how fine-grained. We do have this on our todo for early this year!

**Comment by ddsky** [comment]
That works now: https://worldnewsapi.com/docs/search-news/ via `categories` parameter.
