### ISSUE TITLE
Filtering by country without filtering by language doesn't yield all results that it should (it only yields English articles)

### ISSUE THREAD

**Issue by Boscop** [ddsky/world-news-api-clients#6]
If I search for news using `source-countries=bg`:
`https://api.worldnewsapi.com/search-news?api-key=<key>&earliest-publish-date=2024-01-01%2000:00:00&sort=publish-time&sort-direction=desc&source-countries=bg&number=100`
I get: `"available": 125,`.
Which suggests there are only 125 news articles in Bulgaria after the given timestamp.
But it turns out that's not the case! If I filter by language, I get way more:
`https://api.worldnewsapi.com/search-news?api-key=<key>&earliest-publish-date=2024-01-01%2000:00:00&sort=publish-time&sort-direction=desc&language=bg&number=100`
I get `"available": 1943,`
How can that be? The only logical explanation (for why these articles didn't occur in the first search result but in the second) is if their language is `bg` but their country is not `bg`! 
So I tested this hypothesis by setting both language and country to `bg`:
`https://api.worldnewsapi.com/search-news?api-key=<key>&earliest-publish-date=2024-01-01%2000:00:00&sort=publish-time&sort-direction=desc&source-countries=bg&language=bg&number=100`
Then I get: `"available": 1943,`

Which means basically that all news articles in Bulgarian language came from Bulgaria (unsurprisingly).

**BUT: Then why didn't they show up in the first API result that only filters by country?**

In the first search result, I only seem to get articles in English (even though I have not specified a language filter to restrict it to English)!

This suggests that, if I don't pass a language filter, it filters by English articles. Is that true? This should not happen. (After all, if I want English articles, I'd set the filter to English. If I want articles in any language, I omit the language filter.)

**Comment by ddsky** [comment]
@Boscop default language if nothing is given is in fact **en**. The reason being that leaving it out slows requests down but you are right that omitting it should give all results. We change the logic in the next update to exactly that. Will be live within the next 7 days.

**Comment by Boscop** [comment]
Thanks, I appreciate it!
