### ISSUE TITLE
Searching for news ordered by publish time descendingly takes forever when earliest-publish-date is not present

### ISSUE THREAD

**Issue by Boscop** [ddsky/world-news-api-clients#7]
If I do this `https://api.worldnewsapi.com/search-news?api-key=<key>&number=10&sort=publish-time&sort-direction=desc` 
it takes a **very long time** to load.
Especially compared to adding a earliest-publish-date filter like
`https://api.worldnewsapi.com/search-news?api-key=<key>&number=10&sort=publish-time&sort-direction=desc&earliest-publish-date=2024-01-01%2000:00:00`
which loads instantly.

Ideally the first query should load equally fast.
After all, it corresponds to a SQL query that has a clause like `ORDER BY publish_time DESC LIMIT 10`.
This would be very fast (if there's an index on the `publish_time` column, which there should be), and it would only load 10 records from the DB.
BUT: It seems the backend only includes the `ORDER BY publish_time` and not the `LIMIT 10`, then loads the whole set from the DB and applies the limit as a post-processing step, maybe in order to be able to calculate the `available` value from this set (?)
It would be faster to run two queries, one with limit and one `count(*)` to get `available`.
Then both URLs would load equally fast.

Apart from idealism, the reason why it would be better if the first query also loads fast is, to not have to make up a suitable value for `earliest-publish-date`, to allow users to paginate arbitrarily far back in time.

**Comment by ddsky** [comment]
We have improved the sorting time for queries with a lot of results. Also it is required to send at least one filtering parameter, i.e. `https://api.worldnewsapi.com/search-news?api-key=<key>&number=10&sort=publish-time&sort-direction=desc` is no longer allowed, it must be filtered by text, language or anything else but not getting *all* news (of which there are millions) and sort them by time.
